import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const DATA_PATH = join(ROOT, "data", "energy_weather.csv");
const REPORT_PATH = join(ROOT, "reports", "forecast-report.md");
const TEST_HORIZON = 7;
const SEASON_LENGTH = 7;

function parseCsv(text) {
  const lines = text.trim().split(/\r?\n/);
  const headers = lines[0].split(",");

  return lines.slice(1).map((line) => {
    const values = line.split(",");
    const row = Object.fromEntries(headers.map((header, index) => [header, values[index]]));

    return {
      date: row.date,
      temperatureC: Number(row.temperature_c),
      humidityPct: Number(row.humidity_pct),
      demandKwh: Number(row.demand_kwh)
    };
  });
}

function movingAverageForecast(history, horizon, windowSize = SEASON_LENGTH) {
  const predictions = [];
  const values = history.slice();

  for (let step = 0; step < horizon; step += 1) {
    const window = values.slice(-windowSize);
    const prediction = average(window);
    predictions.push(prediction);
    values.push(prediction);
  }

  return predictions;
}

function seasonalNaiveForecast(history, horizon, seasonLength = SEASON_LENGTH) {
  if (history.length < seasonLength) {
    throw new Error("Seasonal naive needs at least one full season of history.");
  }

  return Array.from({ length: horizon }, (_, index) => history[history.length - seasonLength + (index % seasonLength)]);
}

function linearTrendForecast(history, horizon) {
  const n = history.length;
  const xs = Array.from({ length: n }, (_, index) => index);
  const xMean = average(xs);
  const yMean = average(history);
  const numerator = xs.reduce((sum, x, index) => sum + (x - xMean) * (history[index] - yMean), 0);
  const denominator = xs.reduce((sum, x) => sum + (x - xMean) ** 2, 0);
  const slope = denominator === 0 ? 0 : numerator / denominator;
  const intercept = yMean - slope * xMean;

  return Array.from({ length: horizon }, (_, index) => intercept + slope * (n + index));
}

function mae(actual, predicted) {
  return average(actual.map((value, index) => Math.abs(value - predicted[index])));
}

function mape(actual, predicted) {
  return average(actual.map((value, index) => Math.abs((value - predicted[index]) / value))) * 100;
}

function average(values) {
  return values.reduce((sum, value) => sum + value, 0) / values.length;
}

function round(value, digits = 2) {
  return Number(value.toFixed(digits));
}

function addDays(dateText, days) {
  const date = new Date(`${dateText}T00:00:00Z`);
  date.setUTCDate(date.getUTCDate() + days);
  return date.toISOString().slice(0, 10);
}

function evaluateModels(rows) {
  const splitIndex = rows.length - TEST_HORIZON;
  const train = rows.slice(0, splitIndex).map((row) => row.demandKwh);
  const test = rows.slice(splitIndex).map((row) => row.demandKwh);

  const models = [
    ["moving_average_7", movingAverageForecast(train, TEST_HORIZON)],
    ["seasonal_naive_7", seasonalNaiveForecast(train, TEST_HORIZON)],
    ["linear_trend", linearTrendForecast(train, TEST_HORIZON)]
  ];

  return models
    .map(([name, predictions]) => ({
      name,
      predictions,
      mae: mae(test, predictions),
      mape: mape(test, predictions)
    }))
    .sort((a, b) => a.mae - b.mae);
}

function buildReport(rows, results, futureForecast) {
  const testRows = rows.slice(-TEST_HORIZON);
  const best = results[0];
  const metricRows = results
    .map((result) => `| ${result.name} | ${round(result.mae)} | ${round(result.mape)}% |`)
    .join("\n");
  const backtestRows = testRows
    .map((row, index) => `| ${row.date} | ${row.demandKwh} | ${round(best.predictions[index])} |`)
    .join("\n");
  const futureRows = futureForecast
    .map((item) => `| ${item.date} | ${round(item.demandKwh)} |`)
    .join("\n");

  return `# Forecast Report\n\nGenerated by \`npm run forecast\`.\n\n## Dataset\n\n- Rows: ${rows.length}\n- Date range: ${rows[0].date} to ${rows[rows.length - 1].date}\n- Target: daily demand in kWh\n- Holdout: final ${TEST_HORIZON} days\n\n## Model Metrics\n\n| Model | MAE | MAPE |\n| --- | ---: | ---: |\n${metricRows}\n\nBest model by MAE: \`${best.name}\`.\n\n## Holdout Backtest For Best Model\n\n| Date | Actual kWh | Predicted kWh |\n| --- | ---: | ---: |\n${backtestRows}\n\n## Next 7-Day Forecast\n\n| Date | Forecast kWh |\n| --- | ---: |\n${futureRows}\n\n## Notes\n\nThese baselines are intentionally simple. On this small weekly dataset, the seasonal naive model is expected to be competitive because it preserves the weekday pattern.\n`;
}

function run() {
  const rows = parseCsv(readFileSync(DATA_PATH, "utf8"));
  const results = evaluateModels(rows);
  const best = results[0];
  const history = rows.map((row) => row.demandKwh);
  const forecastValues = best.name === "moving_average_7"
    ? movingAverageForecast(history, TEST_HORIZON)
    : best.name === "seasonal_naive_7"
      ? seasonalNaiveForecast(history, TEST_HORIZON)
      : linearTrendForecast(history, TEST_HORIZON);
  const lastDate = rows[rows.length - 1].date;
  const futureForecast = forecastValues.map((value, index) => ({
    date: addDays(lastDate, index + 1),
    demandKwh: value
  }));

  const report = buildReport(rows, results, futureForecast);
  writeFileSync(REPORT_PATH, report);

  return { rows, results, futureForecast, report };
}

function verify(output) {
  const failures = [];

  if (output.rows.length !== 28) failures.push("Expected 28 data rows.");
  if (output.results.length !== 3) failures.push("Expected 3 model results.");
  if (output.futureForecast.length !== TEST_HORIZON) failures.push("Expected 7 forecast rows.");
  if (!output.results.every((result) => Number.isFinite(result.mae) && result.mae >= 0)) failures.push("MAE values must be finite and non-negative.");
  if (!output.results.every((result) => Number.isFinite(result.mape) && result.mape >= 0)) failures.push("MAPE values must be finite and non-negative.");
  if (!output.report.includes("# Forecast Report")) failures.push("Report was not generated correctly.");

  if (failures.length > 0) {
    throw new Error(`Verification failed:\n${failures.map((failure) => `- ${failure}`).join("\n")}`);
  }
}

const output = run();
const shouldVerify = process.argv.includes("--verify");

if (shouldVerify) {
  verify(output);
  console.log("Verification passed.");
} else {
  console.log(`Forecast report written to ${REPORT_PATH}`);
  console.log(`Best model: ${output.results[0].name} (MAE ${round(output.results[0].mae)}, MAPE ${round(output.results[0].mape)}%)`);
}
